### PR TITLE
[DNM, waiting for review] Bump kustomize to v5.0.1

### PR DESCRIPTION
**Pull request by ramperher**
- From what I can see, kustomize version for k8s 1.27 is v5.0.1: https://github.com/kubernetes-sigs/kustomize#kubectl-integration . And latest release available is v5.2.1: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.2.1. Let's move to v5.0.1 in this case.
- Removing kustomize line from go.mod and go.sum files in cnf-app-mac-operator, they look like to be deprecated

### CODE REVIEW

**Comment by ramperher** [comment]
Debug job passed the installation and the testing but it's failing in a last-minute MCP check, because one of the nodes was in Ready,SchedulingDisabled status: https://www.distributed-ci.io/jobs/6414fc86-0c5c-4278-8d98-60ba503b1ba7/jobStates?sort=date&task=cb345f56-653a-45a6-8a34-c91a6ee26bd5

```
[kni@provisioner.cluster6.dfwt5g.lab ~]$ oc get nodes
NAME       STATUS                     ROLES                  AGE   VERSION
master-0   Ready                      control-plane,master   12h   v1.28.3+20a5764
master-1   Ready                      control-plane,master   12h   v1.28.3+20a5764
master-2   Ready                      control-plane,master   12h   v1.28.3+20a5764
worker-0   Ready                      worker                 11h   v1.28.3+20a5764
worker-1   Ready                      worker                 11h   v1.28.3+20a5764
worker-2   Ready                      worker                 11h   v1.28.3+20a5764
worker-3   Ready,SchedulingDisabled   worker                 11h   v1.28.3+20a5764

```

The change is ready for review anyway

**Comment by tonyskapunk** [comment]
> * From what I can see, kustomize version for k8s 1.27 is v5.0.1: https://github.com/kubernetes-sigs/kustomize#kubectl-integration . And latest release available is v5.2.1: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.2.1. Let's move to v5.0.1 in this case.
> 
>     * Removing kustomize line from go.mod and go.sum files in cnf-app-mac-operator, they look like to be deprecated

Is there a reason to update kustomize?

For operators created with operator-sdk is best to align to what operators-sdk version suggest, in the case of v1.31.0 (the version used in here) the kustomize version is still 3.8.7 or at least is what I see when creating a new operator from scratch:

```
❯ operator-sdk version
operator-sdk version: "v1.31.0", commit: "e67da35ef4fff3e471a208904b2a142b27ae32b1", kubernetes version: "1.26.0", go version: "go1.19.11", GOOS: "linux", GOARCH: "amd64"

❯ operator-sdk init --domain example.com --repo example.com && grep ^KUSTOMIZE_VERSION Makefile
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.14.1
Update dependencies:
$ go mod tidy
Next: define a resource with:
$ operator-sdk create api
KUSTOMIZE_VERSION ?= v3.8.7
```

Digging into the upgrade documentation I do see a suggestion to update to [kustomize 4.5.5, **but** only for helm and ansible](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.23.0/#ansiblev1helmv1-upgrade-kustomize-versions-from-v387-to-v455) based operators, the other operators not this one.

**Comment by ramperher** [comment]
Hi @tonyskapunk, I was just following [CILAB-1282](https://issues.redhat.com/browse/CILAB-1282), where it was suggested to migrate to a more recent version of Kustomize. But honestly, your comment makes totally sense.

Now I've seen operator-sdk has released v1.32.0, but it looks like it's still using Kustomize 3.8.7:

```
$ operator-sdk version
operator-sdk version: "v1.32.0", commit: "4dcbbe343b29d325fd8a14cc60366335298b40a3", kubernetes version: "1.26.0", go version: "go1.19.13", GOOS: "linux", GOARCH: "amd64"

$ operator-sdk init --domain example.com --repo example.com && grep ^KUSTOMIZE_VERSION Makefile
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.14.1
Update dependencies:
$ go mod tidy
Next: define a resource with:
$ operator-sdk create api
KUSTOMIZE_VERSION ?= v3.8.7
```

Maybe we can do the following: update operator-sdk to use v1.32.0, and hold on this change and wait for @tkrishtop to check it we really need to update Kustomize, since she opened the Jira card.

**Comment by ramperher** [comment]
Here's the change to update to new operator-sdk version: https://github.com/openshift-kni/example-cnf/pull/26, let's firstly check that and wait for this other one to confirm what to do.

**Pull request closed without merging**
