### PR TITLE
Fix fallback to old method to gather MAC addresses

### PR DESCRIPTION
**Pull request by ramperher**
We will use the legacy method if:

- No network-status annotation is detected in the pods under test
- Even having the network-status annotation, "mac" attribute is not present

Also, in DPDK 23.11, differently than 19.11, MAC addresses in the testpmd logs are provided in opposite order, so the binding between PCI and MAC addresses must respect that fact

### CODE REVIEW

**Comment by ramperher** [comment]
> from change [dci-labs/dallas-config#130](https://github.com/dci-labs/dallas-config/pull/130):
> 
> * FAILURE https://www.distributed-ci.io/jobs/2937559d-de38-4717-9625-c33b09185865/jobStates

In fact this case is working, I've just being testing in OCP 4.14 to confirm the annotation's logic is triggered and it's working.
I'm still waiting for the OCP 4.12 job

**Comment by ramperher** [comment]
> from change [dci-labs/dallas-config#130](https://github.com/dci-labs/dallas-config/pull/130):
> 
> * SUCCESS https://www.distributed-ci.io/jobs/548e1bf8-5bee-4e14-9feb-d4333370fc7d/jobStates

Direct mode is now working after including https://github.com/rh-nfv-int/nfv-example-cnf-deploy/pull/54 to wait for containers to be ready, it looks like we're facing with race conditions in the code. This is ready for review. I'm testing LB mode in parallel

**Comment by ramperher** [comment]
> from change [dci-labs/dallas-pipelines#1063](https://github.com/dci-labs/dallas-pipelines/pull/1063):
> 
> * FAILURE https://www.distributed-ci.io/jobs/6aae836e-4024-4491-926f-6dc7b5d1004d/jobStates
> * FAILURE https://www.distributed-ci.io/jobs/216c08fc-a8e8-44fe-8990-596f96bc01a3/jobStates

I need to fix this, I've seen what's failing in OCP 4.12, then this will move to ready for review.

**Comment by ramperher** [comment]
The job I'm currently testing is about to pass and this legacy method to retrieve MAC-PCI address is then working, but I need to test it with multiple SRIOV network in the testpmd-app pod, because there it will fail right now. In this test, I just used one SRIOV network.

**Comment by ramperher** [comment]
Launched a job now, it's about to pass. I've checked that, now, the MAC-PCI binding is correct, comparing what we extracted from the containers with the network annotations we use (I've tested this in OCP 4.15):

Annotations output:

```
                    },{
                        "name": "example-cnf/intel-numa0-net1",
                        "interface": "net1",
                        "mac": "9e:df:77:f7:9f:55",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:03.4"
                            }
                        }
                    },{
                        "name": "example-cnf/intel-numa0-net2",
                        "interface": "net2",
                        "mac": "8a:f2:e8:68:d8:71",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:37:03.0"
                            }
                        }
                    }]

```

CNFAppMac CR:

```
$ oc describe cnfappmac
Name:         testpmd-app-7d5599776b-lrlb4
Namespace:    example-cnf
Labels:       <none>
Annotations:  <none>
API Version:  examplecnf.openshift.io/v1
Kind:         CNFAppMac
Metadata:
  Creation Timestamp:  2024-03-21T15:23:14Z
  Generation:          1
  Owner References:
    API Version:           v1
    Block Owner Deletion:  false
    Controller:            true
    Kind:                  Pod
    Name:                  testpmd-app-7d5599776b-lrlb4
    UID:                   e3e13f63-c4fb-45a7-9c9d-3a5e44c12a2f
  Resource Version:        465535
  UID:                     b24e819d-0ba0-4062-8fa6-233d8a0a7d92
Spec:
  Hostname:  testpmd-app-7d5599776b-lrlb4
  Node:      worker-1
  Resources:
    Devices:
      Mac:  9E:DF:77:F7:9F:55
      Pci:  0000:37:03.4
      Mac:  8A:F2:E8:68:D8:71
      Pci:  0000:37:03.0
    Name:   intel-numa0-net1

```

I'll remove the debug code to force this behavior and this will be ready for review now.

**Review by manurodriguez — APPROVED** [review]
Thanks

**Pull request merged**
