### PR TITLE
Fix testpmd-lb build to ensure the digests for app-testpmd and app-listener

### PR DESCRIPTION
**Pull request by tkrishtop**
The same build fix for testpmd as we already put in place for [trex-operator](https://github.com/openshift-kni/example-cnf/pull/14/files).

### CODE REVIEW

**Comment by tkrishtop** [comment]
check dallas ocp-4.13-vanilla example-cnf

**Comment by tkrishtop** [comment]
Test-Hints: force-build=true

**Comment by tkrishtop** [comment]
check dallas ocp-4.13-vanilla example-cnf

**Comment by tkrishtop** [comment]
The change is tested ok, testpmd-lb images are built

```
cp roles/loadbalancer/defaults/main.yml.in roles/loadbalancer/defaults/main.yml
DIGEST=$(skopeo inspect docker://quay.io/rh-nfv-int/testpmd-container-app-testpmd:v0.2.4-pr22.96e6c670|jq -r .Digest) && [ -n "${DIGEST}" ] && sed -i -e "s/testpmd-container-app-testpmd@.*/testpmd-container-app-testpmd@${DIGEST}\"   # v0.2.4-pr22.96e6c670/" roles/loadbalancer/defaults/main.yml
DIGEST=$(skopeo inspect docker://quay.io/rh-nfv-int/testpmd-container-app-listener:v0.2.4-pr22.96e6c670|jq -r .Digest) && [ -n "${DIGEST}" ] && sed -i -e "s/testpmd-container-app-listener@.*/testpmd-container-app-listener@${DIGEST}\"   # v0.2.4-pr22.96e6c670/" roles/loadbalancer/defaults/main.yml
```

and published in quay: 
https://quay.io/repository/rh-nfv-int/testpmd-container-app-testpmd?tab=tags
https://quay.io/repository/rh-nfv-int/testpmd-container-app-listener?tab=tags

and the example-cnf works fine.

@betoredhat I think we're safe to merge.

**Review by betoredhat — APPROVED** [review]
LGTM, thanks

**Pull request merged**
