### PR TITLE
remove 1 external dep for testpmd-container-app

### PR DESCRIPTION
**Pull request by fredericlepied**
change the dependency on https://github.com/krsacme/testpmd-as-load-balancer.git to a local patch

Depends-On: 28600

### CODE REVIEW

**Comment by fredericlepied** [comment]
check dallas ocp-4.13-vanilla example-cnf

**Comment by fredericlepied** [comment]
check dallas ocp-4.13-vanilla example-cnf

**Comment by fredericlepied** [comment]
check dallas ocp-4.13-vanilla example-cnf

**Comment by fredericlepied** [comment]
check dallas ocp-4.12-vanilla example-cnf

**Comment by fredericlepied** [comment]
check dallas ocp-4.12-vanilla example-cnf

**Comment by fredericlepied** [comment]
check dallas ocp-4.12-vanilla example-cnf example-cnf:ansible_extravars=do_cnf_cert:false example-cnf:ansible_extravars=preflight_containers_to_certify:[] example-cnf:ansible_extravars=preflight_operators_to_certify:[]

**Comment by fredericlepied** [comment]
check dallas ocp-4.12-vanilla example-cnf example-cnf:ansible_extravars=do_cnf_cert:false example-cnf:ansible_extravars=preflight_containers_to_certify:[] example-cnf:ansible_extravars=preflight_operators_to_certify:[] example-cnf:ansible_extravars=tests_to_verify:[]

**Comment by capolrik** [comment]
from the last execution, it looks good to me

**Pull request merged**
