### PR TITLE
DPDK container version update

### PR DESCRIPTION
**Pull request by ramperher**
- Updating dpdk container to latest stable one, 4.14, as recommended in nfv-tech group
- Right now we're using the 19.11 binary and latest is 23.11 (currently RHEL/RHCOS RPM includes 22.11 and moving now to 23.11), but we have a tight dependency with https://github.com/krsacme/testpmd-as-load-balancer, which is based on 19.11. Not changing that for the moment

### CODE REVIEW

**Comment by ramperher** [comment]
check dallas ocp-4.11-vanilla example-cnf

**Comment by ramperher** [comment]
Apparently, using DPDK v4.14 container image is not making any issue in old OCP releases, let's try with OCP 4.14 now, just to confirm.

**Comment by ramperher** [comment]
check dallas ocp-4.14-vanilla example-cnf

**Comment by ramperher** [comment]
I'll address the binary update in a separate change, since we need to update the DPDK code based on the work already done here: https://github.com/krsacme/testpmd-as-load-balancer. I'll wait for the end of the current job but it should work, this is ready for review.

**Review by capolrik — APPROVED** [review]

**Pull request merged**
